__default__:
    n_cpu: "-pe parallel_smp "
    mem: "-l mem_free=4G"
    export_env: "-V"
    cwd: "-cwd"
    logerror: "-e "
    log: "-o "
    queue: "-q normal.q"
    jobname: "{rulename}.{name}.{jobid}"

bwaIndex:
    queue: "-q short.q"
bwaAln:
    mem: "-l mem_free=4G"
bwaSamse:
    mem: "-l mem_free=4G"
samtoolsfilter:
    mem: "-l mem_free=4G"
samtoolsMerge:
    mem: "-l mem_free=4G"
getLibarySizesRNA:
    mem: "-l mem_free=8G"
mergeCSVfiles:
    queue: "-q short.q"
filterBAMFiles:
    mem: "-l mem_free=8G"
countOnBAM:
    mem: "-l mem_free=10G"
mergeResume:
    queue: "-q short.q"
plotBarPlot:
    mem: "-l mem_free=10G"
    queue: "-q short.q"
plotBarPlotScale:
    mem: "-l mem_free=10G"
    queue: "-q short.q"
mergePlot:
    queue: "-q short.q"
